[rule]
author = ["Garrett McGuire"]
description = """Insert description here"""
from = "now-6m"
language = "eql"
license = "Elastic License v2"
name = "Insert Name Here"
note = "Insert Analysis Notes Here"
risk_score = 47
severity = "medium"
tags = ["Example", "Tag"]
type = "eql"

query = '''
process where host.os.type == "windows" and event.type == "start" and
  process.name: ("powershell.exe", "pwsh.exe", "powershell_ise.exe") and
  process.command_line : ("*MailboxExportRequest*", "*-Mailbox*-ContentFilter*")
'''


[[rule.threat]] #Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1114"
name = "Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/"
[[rule.threat.technique.subtechnique]]
id = "T1114.002"
name = "Remote Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/002/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
