[rule]
author = ["Garrett McGuire"]
description = """Triggers when more than 1000 web requests are sent to a server"""
from = "now-6m"
language = "eql"
license = "Elastic License v2"
name = "Excessive Web Traffic"
risk_score = 47
severity = "low"
type = "threshold"

query = '''
event.dataset : "zeek.http" 
'''

[rule.threshold]
field = ["source.ip"]
value = 1000

[[rule.threat]] #Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "hhttps://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"
