name: TOML/MITRE Validation

on:
  push:
    paths:
      - "**.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: python development/validation.py
      - run: python development/mitre.py
